#!/bin/bash



#------------------------------------------------#
#-      Show Configure Network Asset Menu       -#
#------------------------------------------------#
show_configure_network_asset_menu(){

    #  Start loop
    BREAK_CONFIGURE_ASSET_MENU=0
    while [ $BREAK_CONFIGURE_ASSET_MENU -le 0 ]; do

        #  Clear the screen
        clear

        #  Print the menu
        echo 'Configure Network Asset List'
        echo '----------------------------'

        echo '----------------------------'
        echo 'q) Back'
        echo -n 'input: '

        #  Read input
        read CONF_INPUT

        case $CONF_INPUT in 

            'q' | 'Q' )
                BREAK_CONFIGURE_ASSET_MENU=1
                ;;
        esac

    done

}

#--------------------------------------#
#-      Show Network Asset Menu       -#
#--------------------------------------#
show_network_asset_menu(){
    
    #  Start loop
    BREAK_NETWORK_ASSET_MENU=0
    while [ $BREAK_NETWORK_ASSET_MENU -le 0 ]; do
        
        # Clear the screen
        clear

        #  Print the menu items
        echo 'Network Asset List'
        echo '------------------'
        
        
        #  Print the table
        if [ -f "/var/tmp/file_list.txt" ]; then
            cat "/var/tmp/file_list.txt"
        else
            echo ''
            echo 'No Network Assets Found'
            echo ''
        fi

        
        #  Print the footer
        echo '------------------'
        echo 'q) Back, c) Configure'


        #  Get input
        read NA_INPUT

        #  Check input
        case $NA_INPUT in

            #  Quit Menu
            'q' | 'Q' )
                BREAK_NETWORK_ASSET_MENU=1
                ;;

            #  Configure Menu
            'c' | 'C' )
                show_configure_network_asset_menu
                ;;

        esac
    
    done

}


#---------------------------------#
#-        Print Main Menu        -#
#---------------------------------#
show_main_menu(){

    BREAK_MAIN_MENU=0
    while [ $BREAK_MAIN_MENU -le 0 ]; do
        
        #  Clear the screen
        clear

        #  Print the menu items
        echo 'Network Monitor'
        echo '---------------'
        echo '1.  Show Network Assets'
        echo 'q.  Quit Application'
        echo -n 'input: '
        
        # Get input
        read INPUT

        #  Check input
        case $INPUT in 
            
            #  Show Network Assets
            "1" )    
                show_network_asset_menu
                ;;

            #  Quit Application
            "q" | "Q" )
                BREAK_MAIN_MENU=1
                ;;

        esac

    done


}


#-------------------------------#
#-        Main Function        -#
#-------------------------------#
show_main_menu

