//
// Created by Marvin Smith on 1/1/18.
//

#ifndef OPENCL_COORDINATE_CONVERTER_COORDINATE_UTM_HPP
#define OPENCL_COORDINATE_CONVERTER_COORDINATE_UTM_HPP

#endif //OPENCL_COORDINATE_CONVERTER_COORDINATE_UTM_HPP
