#!/usr/bin/env python

import sys

#------------------------------#
#-     Usage Instructions     -#
#------------------------------#
def usage():
	
	print('usage: ' + sys.argv[0] + ' [options] [binary string]');
	print('   Convert a decimal number into a binary equivalent');
	print('')
	print('   options:');
	print('   -h : Print help instructions');
	print('   -l [int] : Force a bit length (AKA Give leading zeros).');
	print('');

#---------------------------#
#-      Main Function      -#
#---------------------------#
def main():
	
	#  parse command line option
	if len(sys.argv) <= 1:
		print('No input arguments. Please provide a proper argument.\n');
		usage();
		exit();
	
	#  Parse all input arguments 
	args = sys.argv[1:]
	bitLength = 0;
	while len(args) > 0:

		#  Get the next argument
		arg = args[0];
		args = args[1:];

		#  Show usage instructions
		if arg == '-h' or arg == '--help':
			usage();
			exit();

		#  Force bit length
		elif arg == '-l':
			bitLength = int(args[0]);
			args = args[1:];
	
		#  Get value to convert
		else:
			print(str(bin(int(arg)))[2:].zfill(bitLength));

#-----------------------------#
#-      Program Start        -#
#-----------------------------#
if __name__ == "__main__":
	main();

